tostring row, gen(question)
gen scale = question

replace scale = "Development Materials" if question == "18" | question == "19" | question == "24" | question == "25" | question == "26" | question == "27" | question == "28" | question == "30" | question == "31" | question == "32" | question == "33" | question == "34" | question == "45"
replace scale = "Family Culture" if question == "4" | question == "5" | question == "6"
replace scale = "Lack of Hostility" if question == "12" | question == "13" | question == "14" | question == "15" | question == "16" | question == "17"
replace scale = "Learning Stimulation" if question == "1" | question == "2" | question == "3" | question == "7" | question == "29" | question == "35" | question == "36" | question == "37" | question == "38" | question == "39" | question == "42"
replace scale = "Opportunities for Variety" if question == "21" | question == "22" | question == "23" | question == "41" | question == "43" | question == "44"
replace scale = "Parental Warmth" if question == "8" | question == "9" | question == "10" | question == "11"
replace scale = "N/S" if question == "20" | question == "40"

gen scale_row = .
replace scale_row = 1 if scale == "Total Score"
replace scale_row = 2 if scale == "Learning Stimulation"
replace scale_row = 3 if scale == "Development Materials"
replace scale_row = 4 if scale == "Opportunities for Variety"
replace scale_row = 5 if scale == "Lack of Hostility"
replace scale_row = 6 if scale == "Parental Warmth"
replace scale_row = 7 if scale == "Family Culture"

replace question = "Parent spontaneously vocalized to child twice" if question == "1"
replace question = "Parent responds verbally to child's verbalization" if question == "2"
replace question = "Parent tells child name of object or person during visit" if question == "3"
replace question = "Parent's speech is distinct and audible" if question == "4"
replace question = "Parent initiates verbal exchanges with visitor" if question == "5"
replace question = "Parent converses freely and easily" if question == "6"
replace question = "Parent permits child to engage in messy play" if question == "7"
replace question = "Parent spontaneously praises child at least twice" if question == "8"
replace question = "Parent's voice conveys positive feelings towards child" if question == "9"
replace question = "Parent caresses or kisses child at least once" if question == "10"
replace question = "Parent responds positively to praise of child offered by visitor" if question == "11"
replace question = "Parent does not shout at child" if question == "12"
replace question = "Parent does not express annoyance with or hostility to child" if question == "13"
replace question = "Parent neither slaps nor spanks child during visit" if question == "14"
replace question = "No more than one instance of physical punishment during past week" if question == "15"
replace question = "Parent does not scold or criticize child during visit" if question == "16"
replace question = "Parent does not interfere or restrict child more than 3 times" if question == "17"
replace question = "At least ten books are present & visible" if question == "18"
replace question = "Family has a pet" if question == "19"
replace question = "Substitute care is provided by one of 3 regular substitutes" if question == "20"
replace question = "Child is taken to grocery store at least once/week" if question == "21"
replace question = "Child gets out of house at least 4 times/week" if question == "22"
replace question = "Child is taken regularly to doctor's office or clinic" if question == "23"
replace question = "Child has a special place for toys and treasures" if question == "24"
replace question = "Child's play environment is safe" if question == "25"
replace question = "Muscle activity toys or equipment" if question == "26"
replace question = "Push or pull toy" if question == "27"
replace question = "Stroller or walker, kiddie car, scooter, or tricycle" if question == "28"
replace question = "Parent provides toys for child during visit" if question == "29"
replace question = "Learning equipment appropriate to age - cuddly toys or role-playing toys" if question == "30"
replace question = "Learning facilitator - mobile, table and chairs, high chair, play pen" if question == "31"
replace question = "Simple eye-hand coordination toys" if question == "32"
replace question = "Complex eye-hand coordination toys (those permitting combination)" if question == "33"
replace question = "Toys for literature and music" if question == "34"
replace question = "Parent keeps child in visual range, looks at often" if question == "35"
replace question = "Parent talks to child while doing household work" if question == "36"
replace question = "Parent consciously encourages developmental advance" if question == "37"
replace question = "Parent invests maturing toys with value via personal attention" if question == "38"
replace question = "Parent structures child's play periods" if question == "39"
replace question = "Parent provides toys that challenge child to develop new skills" if question == "40"
replace question = "Father provides some care daily" if question == "41"
replace question = "Parent reads stories to child at least 3 times weekly" if question == "42"
replace question = "Child eats at least one meal per day with mother and father" if question == "43"
replace question = "Family visits relatives or receives visits once a months or so" if question == "44"
replace question = "Child has 3 or more books of his/her own" if question == "45"

keep if inlist(scale_row, 2,3,4,5,6)
