tostring row, gen(question)
gen scale = question

replace scale = "Development Materials" if question == "1" | question == "2" | question == "3" | question == "4" | question == "5" | question == "6" | question == "7" | question == "12" | question == "43"
replace scale = "Family Culture" if question == "8" | question == "9" | question == "10" | question == "15" | question == "48"
replace scale = "Housing" if question == "19" | question == "20" | question == "21" | question == "22" | question == "23" | question == "24" | question == "25"
replace scale = "Lack of Hostility" if question == "41" | question == "42" | question == "52" | question == "53" | question == "54" | question == "55"
replace scale = "Learning Stimulation" if question == "11" | question == "13" | question == "14" | question == "16" | question == "27" | question == "28" | question == "29" | question == "33" | question == "34" | question == "35" | question == "36" | question == "37" | question == "38" | question == "39" | question == "40" | question == "47" | question == "49"
replace scale = "Opportunities for Variety" if question == "18" | question == "44" | question == "45" | question == "46" | question == "50" | question == "51"
replace scale = "Parental Warmth" if question == "17" | question == "26" | question == "30" | question == "31" | question == "32"

gen scale_row = .
replace scale_row = 1 if scale == "Total Score"
replace scale_row = 2 if scale == "Learning Stimulation"
replace scale_row = 3 if scale == "Development Materials"
replace scale_row = 4 if scale == "Opportunities for Variety"
replace scale_row = 5 if scale == "Lack of Hostility"
replace scale_row = 6 if scale == "Parental Warmth"
replace scale_row = 7 if scale == "Family Culture"
replace scale_row = 8 if scale == "Housing"

replace question = "Toys that teach color, size, shape" if question == "1"
replace question = "Three or more puzzles" if question == "2"
replace question = "Record player and >5 children's records" if question == "3"
replace question = "Child has toys permitting free expression" if question == "4"
replace question = "Child has toys or games requiring refined movements" if question == "5"
replace question = "Child has toys or games which help teach numbers" if question == "6"
replace question = "Child has at least 10 children's books" if question == "7"
replace question = "At least 10 books are visible in the apartment" if question == "8"
replace question = "Family buys and reads a daily newspaper" if question == "9"
replace question = "Family subscribes to at least one magazine" if question == "10"
replace question = "Child is encouraged to learn shapes" if question == "11"
replace question = "Child has toys that help teach the names of animals" if question == "12"
replace question = "Child is encouraged to learn the alphabet" if question == "13"
replace question = "Parent teaches child simple verbal manners" if question == "14"
replace question = "Mother uses correct grammar and pronunciation" if question == "15"
replace question = "Parent encourages child to talk and takes time to listen" if question == "16"
replace question = "Parent's voice conveys positive feelings to child" if question == "17"
replace question = "Child is permitted choice in breakfast or lunch menu" if question == "18"
replace question = "Building appears safe" if question == "19"
replace question = "Outside play environment appears safe" if question == "20"
replace question = "Interior of apartment not dark or perceptually monotonous" if question == "21"
replace question = "Neighborhood is aesthetically pleasing" if question == "22"
replace question = "House has 100 sq. ft. of living space per person" if question == "23"
replace question = "Rooms are not overcrowded with furniture" if question == "24"
replace question = "House is reasonably clean and minimally cluttered" if question == "25"
replace question = "Parent holds child close 10-15 minutes per day" if question == "26"
replace question = "Parent converses with child at least twice during visit" if question == "27"
replace question = "Parent answers child's questions or requests verbally" if question == "28"
replace question = "Parent usually responds to child's speech" if question == "29"
replace question = "Parent spontaneously praises child's qualities twice during visit" if question == "30"
replace question = "Parent caresses, kisses, or cuddles child during visit" if question == "31"
replace question = "Parent helps child demonstrate some achievement during visit" if question == "32"
replace question = "Child is encouraged to learn colors" if question == "33"
replace question = "Child is encouraged to learn patterned speech (songs, etc.)" if question == "34"
replace question = "Child is encouraged to learn spatial relationships" if question == "35"
replace question = "Child is encouraged to learn numbers" if question == "36"
replace question = "Child is encouraged to learn to read a few words" if question == "37"
replace question = "Some delay of food gratification is expected" if question == "38"
replace question = "TV is used judiciously" if question == "39"
replace question = "Parent introduces visitor to child" if question == "40"
replace question = "Child can express negative feelings without reprisal" if question == "41"
replace question = "Child can hit parent without harsh reprisal" if question == "42"
replace question = "Child has real or toy musical instrument" if question == "43"
replace question = "Child is taken on outing by family member at least every other week" if question == "44"
replace question = "Child has been on trip more than 50 miles during last year" if question == "45"
replace question = "Child has been taken to a museum during past year" if question == "46"
replace question = "Parent encourages child to put away toys without help" if question == "47"
replace question = "Parent uses complex sentences structure and vocabulary" if question == "48"
replace question = "Child's art work is displayed some place in house" if question == "49"
replace question = "Child eats at least one meal per day with mother and father" if question == "50"
replace question = "Parent lets child choose some foods or brands at grocery store" if question == "51"
replace question = "Parent does not scold or derogate child more than once" if question == "52"
replace question = "Parent does not physical restraint during visit" if question == "53"
replace question = "Parent neither slaps nor spanks child during visit" if question == "54"
replace question = "No more than once instance of physical punishment during past week" if question == "55"

keep if inlist(scale_row, 2,3,4,5,6)
