tostring row, gen(question)
gen scale = question

replace scale = "Aggresive Behavior" if inlist(row, 16, 19, 20, 21, 22, 23, 37, 57, 68, 86, 87, 88, 89, 94, 95, 97, 104)
replace scale = "Anxious/Depressed" if inlist(row, 14, 29, 30, 31, 32, 33, 35, 45, 50, 52, 71, 91, 112)
replace scale = "Attention Problems" if inlist(row, 1, 4, 8, 10, 13, 17, 41, 61, 78, 80)
replace scale = "Rule-Breaking Behavior" if inlist(row, 2, 26, 28, 39, 43, 63, 67, 72, 73, 81, 82, 90, 96, 99, 101, 105, 106)
replace scale = "Social Problems" if inlist(row, 11, 12, 25, 27, 34, 36, 38, 48, 62, 64, 79)
replace scale = "Somatic Complaints" if inlist(row, 47, 49, 51, 54, 56, 113, 114, 115, 116, 117, 118, 119)
replace scale = "Thougth Problems" if inlist(row, 9, 18, 40, 46, 58, 59, 60, 66, 70, 76, 83, 84, 85, 92, 100)
replace scale = "Withdrawn/Drepressed" if inlist(row, 5, 42, 65, 69, 75, 102, 103, 111)
replace scale = "Other" if inlist(row, 3, 6, 7, 15, 24, 44, 53, 55, 74, 77, 93, 98, 107, 108, 109, 110, 113)

gen scale_row = . 
replace scale_row = 1 if scale == "Aggresive Behavior"
replace scale_row = 2 if scale == "Anxious/Depressed"
replace scale_row = 3 if scale == "Attention Problems"
replace scale_row = 4 if scale == "Rule-Breaking Behavior"
replace scale_row = 5 if scale == "Social Problems"
replace scale_row = 6 if scale == "Somatic Complaints"
replace scale_row = 7 if scale == "Thougth Problems"
replace scale_row = 8 if scale == "Withdrawn/Drepressed"
replace scale_row = 9 if scale == "Other"

replace question = "1. Acts too young for his/her age" if question == "1"
replace question = "2. Has allergies" if question == "2"
replace question = "3. Argues a lot" if question == "3"
replace question = "4. Has asthma" if question == "4"
replace question = "5. Behaves like opposite sex" if question == "5"
replace question = "6. Bowel movements outside toilet" if question == "6"
replace question = "7. Bragging, boasting" if question == "7"
replace question = "8. Can't concentrate, can't pay attention for long" if question == "8"
replace question = "9. In past 6 months, child can't get mind off certain thoughts" if question == "9"
replace question = "10. Can't sit still, restless, or hyperactive" if question == "10"
replace question = "11. Clings to adults or too dependent" if question == "11"
replace question = "12. Complains of loneliness" if question == "12"
replace question = "13. Confused or seems to be in a fog" if question == "13"
replace question = "14. Cries a lot" if question == "14"
replace question = "15. Cruel to animal" if question == "15"
replace question = "16. Cruelty, bullying, or meanness to others" if question == "16"
replace question = "17. In past 6 months, child day-dreams or gets lost in thoughts" if question == "17"
replace question = "18. Deliberately harms self or attempts suicide" if question == "18"
replace question = "19. Demands a lot of attention" if question == "19"
replace question = "20. Destroys his/her own things" if question == "20"
replace question = "21. Destroys things belonging to his/her family or other children" if question == "21"
replace question = "22. Disobedient at home" if question == "22"
replace question = "23. Disobedient at school" if question == "23"
replace question = "24. Over the past six months, doesn't eat well" if question == "24"
replace question = "25. Doesn't get along with other children" if question == "25"
replace question = "26. Doesn't seem to feel guilty after misbehaving" if question == "26"
replace question = "27. Easily jealous" if question == "27"
replace question = "28. Eats or drinks things that are not food" if question == "28"
replace question = "29. Fears certain animals, situations, or places, other than school" if question == "29"
replace question = "30. Over the past six months, fears going to school" if question == "30"
replace question = "31. Fears he/ she might think or do something bad" if question == "31"
replace question = "32. Feels he/she has to be perfect" if question == "32"
replace question = "33. Feels or complains that no one loves him/her" if question == "33"
replace question = "34. Feels others are out to get him/her" if question == "34"
replace question = "35. Feels worthless or inferior" if question == "35"
replace question = "36. Gets hurt a lot, accident-prone" if question == "36"
replace question = "37. Gets in many fights" if question == "37"
replace question = "38. Over the past six months child gets teased a lot" if question == "38"
replace question = "39. Hangs around with children who get in trouble" if question == "39"
replace question = "40. Hears things that aren't there" if question == "40"
replace question = "41. Impulsive or acts without thinkng" if question == "41"
replace question = "42. Likes to be alone" if question == "42"
replace question = "43. Lying or cheating" if question == "43"
replace question = "44. Bites fingernails" if question == "44"
replace question = "45. Nervous, highstrung, or tense" if question == "45"
replace question = "46. Nervous movements or twitching" if question == "46"
replace question = "47. Over the past six months, child has nightmares" if question == "47"
replace question = "48. Not liked by other children" if question == "48"
replace question = "49. Constipated, doesn't move bowels" if question == "49"
replace question = "50. Too fearful or anxious" if question == "50"
replace question = "51. Feels dizzy" if question == "51"
replace question = "52. Feels too guilty" if question == "52"
replace question = "53. Overeating" if question == "53"
replace question = "54. Over the past six months, child is overtired" if question == "54"
replace question = "55. Overweight" if question == "55"
replace question = "56. Sick without known medical cause" if question == "56"
replace question = "57. Physically attacks people" if question == "57"
replace question = "58. In past 6 months, child picks nose, skin, or other parts of body" if question == "58"
replace question = "59. Plays with own sex parts in public" if question == "59"
replace question = "60. Plays with own sex parts too much" if question == "60"
replace question = "61. Poor school work" if question == "61"
replace question = "62. Poorly coordinated or clumsy" if question == "62"
replace question = "63. Prefers playing with older children" if question == "63"
replace question = "64. Prefers playing with younger children" if question == "64"
replace question = "65. Refuses to talk" if question == "65"
replace question = "66. Repeats certain actions over and over; compulsions" if question == "66"
replace question = "67. Runs away from home" if question == "67"
replace question = "68. Over the past six months, screams a lot" if question == "68"
replace question = "69. Secretive, keeps things to self" if question == "69"
replace question = "70. Sees things that aren't there" if question == "70"
replace question = "71. Self-conscious or easily embarrassed" if question == "71"
replace question = "72. Sets fires" if question == "72"
replace question = "73. Sexual problems" if question == "73"
replace question = "74. Showing off or clowning" if question == "74"
replace question = "75. Shy or timid" if question == "75"
replace question = "76. Sleeps less than most children" if question == "76"
replace question = "77. Sleeps more than most children during day and/or night" if question == "77"
replace question = "78. Smears or plays with bowel movements" if question == "78"
replace question = "79. Speech problem" if question == "79"
replace question = "80. Over the past six months stares blankly" if question == "80"
replace question = "81. Steals at home" if question == "81"
replace question = "82. Steals outside the home" if question == "82"
replace question = "83. Stores up things he/she doesn't need" if question == "83"
replace question = "84. Strange behavior" if question == "84"
replace question = "85. Strange ideas" if question == "85"
replace question = "86. Stubborn, sullen, or irritable" if question == "86"
replace question = "87. Sudden changes in mood or feelings" if question == "87"
replace question = "88. Sulks a lot" if question == "88"
replace question = "89. Suspicious" if question == "89"
replace question = "90. Swearing or obscene language" if question == "90"
replace question = "91. Talks about killing self" if question == "91"
replace question = "92. Over the past six months, child talks or walks in sleep" if question == "92"
replace question = "93. Talks too much" if question == "93"
replace question = "94. Teases a lot" if question == "94"
replace question = "95. Temper tantrums or hot temper" if question == "95"
replace question = "96. Thinks about sex too much" if question == "96"
replace question = "97. Threatens people" if question == "97"
replace question = "98. Thumb-sucking" if question == "98"
replace question = "99. Too concerned with neatness or cleanlinees" if question == "99"
replace question = "100. Trouble sleeping" if question == "100"
replace question = "101. Truancy, skips school" if question == "101"
replace question = "102. Underactive, slow moving, or lacks energy" if question == "102"
replace question = "103. Unhappy, sad or depressed" if question == "103"
replace question = "104. Unusually loud" if question == "104"
replace question = "105. Uses alcohol or drugs" if question == "105"
replace question = "106. Vandalism" if question == "106"
replace question = "107. Wets self during the day" if question == "107"
replace question = "108. Over the past six months, wets the bed" if question == "108"
replace question = "109. Whining" if question == "109"
replace question = "110. Wishes to be of opposite sex" if question == "110"
replace question = "111. Withdrawn, doesn't get involved with others" if question == "111"
replace question = "112. Worrying" if question == "112"
replace question = "56a. Aces or pains without known medical cause" if question == "113"
replace question = "56b. Headaches without known medical cause" if question == "114"
replace question = "56c. Nausea, feels sick without known medical cause" if question == "115"
replace question = "56d. Problems with eyes without known medical cause" if question == "116"
replace question = "56e. Rashes or other skin problems without known medical cause" if question == "117"
replace question = "56f. Stomachaces or cramps without known medical cause" if question == "118"
replace question = "56g. Vomiting, throwing up without known medical cause" if question == "119"

* keep if inlist(scale_row, 1, 2, 3, 4, 5, 6, 7, 8, 9)
